# Generated by Django 3.2.5 on 2021-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LunchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('order', models.TextField(max_length=100)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
